### ISSUE TITLE
PyUnitWizard can not be imported in Windows with Python 3.9 when tests are executed.

### ISSUE THREAD

**Issue by dprada** [uibcdf/PyUnitWizard#18]
The CI GitHub Actions fail in Windows with the following message:

```
Run echo 'import pyunitwizard ; print(pyunitwizard.__version__)' | python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\a\PyUnitWizard\PyUnitWizard\pyunitwizard\__init__.py", line 18, in <module>
    from .main import unit, quantity, get_form, get_value, get_unit, is_quantity, is_unit
  File "D:\a\PyUnitWizard\PyUnitWizard\pyunitwizard\main.py", line 4, in <module>
    from ._private_tools.quantity_or_unit import ArrayLike, QuantityOrUnit, QuantityLike, UnitLike
  File "D:\a\PyUnitWizard\PyUnitWizard\pyunitwizard\_private_tools\quantity_or_unit.py", line 5, in <module>
    import openmm.unit as openmm_unit
  File "C:\Miniconda\envs\test\lib\site-packages\openmm\__init__.py", line 19, in <module>
    from openmm.openmm import *
  File "C:\Miniconda\envs\test\lib\site-packages\openmm\openmm.py", line 13, in <module>
    from . import _openmm
ImportError: DLL load failed while importing _openmm: The specified module could not be found.
Error: Process completed with exit code 1.
```

Apparently, the library path is missing in the session.

**Comment by dprada** [comment]
This issue is duplicated, see https://github.com/uibcdf/PyUnitWizard/issues/22
